---
# tasks file for epel


- name: check our OS is supported
  assert:
    that:
      - ansible_distribution == "CentOS"


- name: check our vars are defined
  assert:
    that:
    - epelrpm is defined
    - epelpath is defined


- name: create epel dir
  file:
    path: "{{ epelpath }}"
    state: directory
    owner: "root"
    group: "{{ ansible_user_id }}"
    mode: '0775'
  become: true


- name: check we have setup rpm
  stat:
    path: "{{ epelpath }}/{{ epelrpm }}"
  register: epelhaverpm
  failed_when: false


- name: setup epel
  block:
    - name: get and check rpm
      get_url:
        url: "{{ epelrpmdlurl }}{{ epelrpm }}"
        dest: "{{ epelpath }}"
        checksum: "{{ lookup('vars', 'epelsha{{ ansible_distribution_major_version }}') }}"
    - name: install the rpm
      yum:
        name: "{{ epelpath }}/{{ epelrpm }}"
        state: present
      become: true
    - name: mark rpm key as trusted
      rpm_key:
        key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
        fingerprint: "{{ lookup('vars', 'epelgpgprint{{ ansible_distribution_major_version }}') }}"
      become: true
  when: not epelhaverpm.stat.exists


- name: check epel files are in place
  block:
    - name: 'yum yum.repos.d file '
      stat:
        path: "/etc/yum.repos.d/epel.repo"
      register: epelcheck_repo
    - name: 'file in /etc/pki/rpm-gpg'
      stat:
        path: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
      register: epelcheck_gpg


- name: check rpm installed ok
  assert:
    that:
        - epelcheck_repo.stat.exists
        - epelcheck_gpg.stat.exists
