---
# tasks file for ms-linux-repo


- name: copy MS GPG Key
  copy:
    src: "{{ msgpgkeyname }}"
    dest: "/etc/pki/rpm-gpg/microsoft.asc"
    mode: 0640
  become: true


- name: add rpm key
  rpm_key:
    key: "/etc/pki/rpm-gpg/microsoft.asc"
    fingerprint: "{{ msgpgkeyid }}"
  become: true


- name: Add MS Yum Repo
  yum_repository:
    name: microsoft-com-prod
    description: Microsoft YUM repo
    baseurl: "https://packages.microsoft.com/rhel/{{ ansible_distribution_major_version }}/prod/"
    gpgcheck: yes
    gpgkey: "file:///etc/pki/rpm-gpg/microsoft.asc"
  become: true
