---
# tasks file for aa-custom


- name: check setup file
  stat:
    path: "{{ aacodepath }}/aa-custom_vars.example.yml"
  register: aavardefault
  failed_when: false


- name: check defaults vars exists
  assert:
    that:
        - aavardefault.stat.exists


# uses first vars file found
- name: include vars files
  include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      - "{{ aacodepath }}/aa-custom_vars.yml"
      - "{{ aacodepath }}/aa-custom_vars.example.yml"


- name: include custom user tasks
  include: usertasks.yml
