---
# tasks file for aa-custom


- name: check setup file
  stat:
    path: "/vagrant/aa-custom_vars.example.yml"
  register: aavardefault
  failed_when: false


# uses first vars file found
- name: include vars files
  include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      - /vagrant/aa-custom_vars.yml
      - /vagrant/aa-custom_vars.example.yml


- name: include custom user tasks
  include: usertasks.yml
  when:
    - "{{ aa_user }} is defined"
