---
# tasks file for aa-custom


- name: change timezone
  timezone:
    name: "{{ aa_user.aavm_timezone }}"
  become: true


- name: create user specified account
  user:
    name: "{{ aa_user.username }}"
    comment: "{{ aa_user.name }}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    create_home: true
  become: true


- name: install users packages
  package:
    name: "{{ item }}"
    state: present
  retries: 3
  with_items: "{{ aa_yum_install }}"
  become: true