---
# tasks file for aa-base


- name: 'upload custom fact script'
  copy:
    dest: "/etc/ansible/facts.d/aainfo.fact"
    mode: 0755
    content: |
      #!/usr/bin/env python3
      # example of ansible custom fact script.
      import os
      import sys
      import platform
      import datetime
      import json

      date = str(datetime.datetime.now())
      gitignore = str(os.path.isdir('/vagrant/gitignore/'))
      aareadmegen = str(os.path.isfile('/home/vagrant/readme.txt'))

      print(json.dumps({
          "time" : date,
          "areadmetext" : aareadmegen,
          "gitignoredir" : gitignore
      }))


- name: "get new custom facts"
  setup: ~


- name: 'check aainfo fact set'
  assert:
    that:
      - ansible_local.aainfo.areadmetext is defined
