---
# tasks file for aa-base


- name: 'Running the role: '
  debug: msg=" {{ role_path|basename }} "


- name: 'change timezone'
  timezone:
    name: "{{ aavm_timezone }}"
  become: true


- name: 'setup folders'
  block:
    - name: 'check folder vars are set'
      assert:
        that:
          - common_dir is defined
    - name: 'Create common folders'
      file:
        path: "{{ item.dir }}"
        state: directory
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
      with_items: "{{ common_dir }}"
      become: true


- name: 'copy dot files to home dir'
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
  with_items: "{{ dotfiles }}"


- name: 'install and remove packages'
  include: packages.yml

- name: 'create a user for dev work'
  include: devuser.yml


- name: 'readme.txt template'
  template:
    src: readme_txt.j2
    dest: ~/readme.txt
    mode: 0644
  changed_when: false


- name: 'custom fact scripts'
  include: aafacts.yml
