---
# tasks file for aa-base


- name: 'Running the role: '
  debug: msg=" {{ role_path|basename }} "


- name: 'Set timezone to Sydney'
  timezone:
    name: Australia/Sydney
  become: true


- name: 'check "Create common folders" vars are defined'
  assert:
    that:
      - common_dir is defined
- name: 'Create common folders'
  file:
    path: "{{ item.dir }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ common_dir }}"
  become: true


- name: 'dot files to home dir'
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
  with_items: "{{ dotfiles }}"


- name: 'install these packages in our default repos'
  package:
    name: "{{ item.add_tool }}"
    state: present
  retries: 2
  with_items: "{{ package_add_tool }}"
  become: true


- name: 'readme.txt template'
  template:
    src: readme_txt.j2
    dest: ~/readme.txt
    mode: 0644
  changed_when: false
