---
# tasks file for docker-ce-centos


- name: check our OS is supported
  assert:
    that:
      - ansible_distribution == "CentOS"


- name: remove old docker if any exists
  yum:
    state: absent
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
  become: true


- name: install Docker requirements
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  become: true


- name: copy yum repo folder
  template:
    src: "docker-ce-repo.j2"
    dest: "/etc/yum.repos.d/docker-ce.repo"
    mode: 0644
    owner: root
    group: root
  become: true


- name: copy gpg key
  copy:
    src: "{{ dockergpgfile }}"
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-DockerCE"
  become: true


- name: Verify the key using a fingerprint before importing
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-DockerCE"
    fingerprint: "{{ dockergpgfinger }}"
  become: true


- name: install DockerCE
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: true


- name: adding ansible user to docker group
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: true
  become: true


# test docker runs
- name: check docker version
  command: "docker --version"
  register: dockerver
  changed_when: false


- name: check docker works
  assert:
    that:
      - "'Docker version' in dockerver.stdout"
      - "dockerver.rc == 0"


- name: start docker
  service:
    name: docker.service
    enabled: true
    state: started
  become: true
